name: Exynos990 Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex libssl-dev \
            build-essential clang lld \
            libncurses-dev dwarves

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build kernel
        run: ./build.sh -m y2s -k y -c n

